

name: Backup Firestore


on:
  schedule:
    - cron: '0 0 * * *'         
env:
  PROJECT_ID: Project_ID        //Google Cloud Project ID
  BUCKET: gs://Your-Bucket      //Google Cloud Storage Bucket 

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{secrets.GCP_SA_KEY}}
          export_default_credentials: true

      - name: Display gcloud info
        run: gcloud info

      - name: Set project ID
        run: gcloud config set project $PROJECT_ID

      - name: Firestore export to Cloud Storage
        run: gcloud firestore export $BUCKET
